export { default as AdminDashbord } from "./AdminDashbord";
export { default as Landing } from "./Landing";
export { default as Login } from "./Login";
export { default as SignUp } from "./SignUp";
export { default as NotFound } from "./NotFound";
export { default as ForgotPassword } from "./ForgotPassword";
export { default as DeviceLimit } from "./DeviceLimit";
export { default as Pricing } from "./Pricing";
export { default as UnAuthorized } from "./UnAuthorized";
